### ISSUE TITLE
IOS can't enabled bitcode

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#100]
I can't activate ENABLED_BITCODE in my build settings, if I do my app won't start here's the error:

`'/Users/samuelhoule/Web/MyProject/project/ios/Pods/iOS-Client-SDK/Output/SelfieSegmentation.framework/SelfieSegmentation' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/samuelhoule/Web/MyProject/project/ios/Pods/iOS-Client-SDK/Output/SelfieSegmentation.framework/SelfieSegmentation' for architecture arm64`

I need to activate bitcode to upload sourcemaps to sentry.

**Comment by 3akat** [comment]
Hey @sam-houle1, we are working in sprints and because we are already mid sprint we are not going to be able to add this to the current sprint. We will be adding this to the next sprint, which means 3-4 weeks time. Of course as we see it as a bug, we will add priority so that we start on it as soon as it is possible.

**Comment by 3akat** [comment]
@sam-houle1 that's true, we will do our best to fix this asap

**Comment by sam-houle1** [comment]
@3akat thanks I appreciate

**Comment by 3akat** [comment]
Hey @sam-houle1. Just a few hours ago we had internal discussion regarding this issue - we can't fix it fast, but we will create a separate release which excludes the feature-cause. Hope to see it until the end of the week.

**Comment by sam-houle1** [comment]
@3akat alright perfect thanks for the heads up !

**Comment by sam-houle1** [comment]
hi @3akat, is this fix ?

**Comment by Bane-D** [comment]
Hi Sam, thank you for your patience so far.

My colleagues would know more, however as I saw your question, I thought to give you the info that I know.

The update that addresses this will be made soon, it was not pushed out yet.

Once it is available one of my colleagues will follow up with you to let you know it is available for you to test it. :)

**Comment by Bane-D** [comment]
Hi Sam,

The code has been updated and should work right for you now.

If you want to use our SDK with standard features (without the background blurring) then for iOS you would:
1. Create podfile within your project
2. add:
```
pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'
```
If you want to use SDK with the background blurring then for iOS you would:
1. Create podfile within your project
2. add:
```
pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :branch => 'blurring'
```

* Please note that background blurring is the one that requires `ENABLED_BITCODE` to be turned on, so in your specific case you should use the first option (without it)

Do let us know how it goes.

**Comment by sam-houle1** [comment]
@Bane-D Do I have to upgrade my ziggeo nom package ? Currently on 1.6.11, So basicly I didn't have the blurring option, so I had nothing to do except enabled bitcode, and I still have the same error.

**Comment by Bane-D** [comment]
Hey Sam, I will check with my colleague, however you will likely need to clean the build first so:

```
$ cd ios
$ rm -rf build
$ xcodebuild clean
```

then try to build it (with the podfile updated - if needed). It should then pull the latest iOS Client SDK version for you.

**Comment by katolykdev** [comment]
@sam-houle1  
If your app needs to set the `ENABLED_BITCODE` option to `Yes`, please add the below code to Pod file.
```pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'```

And reinstall pod.
```pod install```

That sdk was updated several days ago.
Please recheck.

**Comment by sam-houle1** [comment]
@katolykdev @Bane-D Hi, I was able to launch the app on my device, but I still have the same error if I try to use the simulator.

**Comment by katolykdev** [comment]
@sam-houle1  I will check on simulator.

**Comment by katolykdev** [comment]
@sam-houle1  I have checked on simulator, it is working.
Could you send me the screenshot of the error?

**Comment by sam-houle1** [comment]
<img width="1072" alt="Screen Shot 2022-06-01 at 12 52 27 PM" src="https://user-images.githubusercontent.com/44783494/171458614-fa630586-d909-450e-b96f-a5a6d12d2e28.png">

@katolykdev It's the exact same error as before.

**Comment by katolykdev** [comment]
@sam-houle1 Did you install the latest version of iOS-Client-SDK?
Could you tell me the version you installed?

**Comment by sam-houle1** [comment]
@katolykdev Hi, I was wondering if this is something you guys could reproduce, I would rather not have to send my private code base.
