### ISSUE TITLE
Is it possible to handle IOS pods properly

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#101]
From what I can understand, the framework is loaded directly from [this git repo](https://github.com/Ziggeo/iOS-Client-SDK). The problem is every time IOS-Client-SDK has a new version, we have to upgrade this package since the pod configuration always use the latest version. So, if something is breaking inside the framework (which occurs most of the time), we have to upgrade this package and hope that everything function properly.

**Comment by katolykdev** [comment]
You can install Ziggeo SDK of the version you want using below command.
```
pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :branch => '1.1.38'
```
From version 1.1.39
```
pod 'ZiggeoMediaSDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :branch => '1.1.39'
```
