### ISSUE TITLE
How to embed video player on screen

### ISSUE THREAD

**Issue by stachu2k** [Ziggeo/ReactNativeSDK#103]
Hi. I was playing a little bit with this library SDK and a demo app. But still it's not clear for me how to embed a player on a screen in my application. Documentation shows only usefull methods from Ziggeo class, but what about React component with player?

**Comment by katolykdev** [comment]
Hi, @stachu2k 
You can play video using playVideo function.
```Ziggeo.playVideo(videoToken);```

Please check below the demo project.
[ReactNativeDemo.zip](https://github.com/Ziggeo/ReactNativeSDK/files/9063864/ReactNativeDemo.zip)

**Comment by katolykdev** [comment]
Are you trying to use your player instead of using a ziggeo player?
So you want to the video url for playing?

**Comment by stachu2k** [comment]
@katolykdev Yes. Exactly. I want to use Ziggeo as a video player for my own video files hosted on my hosting site.

**Comment by katolykdev** [comment]
You want to use Ziggeo player to play your own video like below?
playVideo(video_url)

**Comment by stachu2k** [comment]
Yes. I tried doing this `Ziggeo.playFromUri("PATH_OR_URL")` but it keeps crashing. I don't know if I am missing something.

**Comment by katolykdev** [comment]
Got it. I will add that function in 2 days.

**Comment by katolykdev** [comment]
Hello, @stachu2k 
Please check on current version `1.6.26`.
Ziggeo.playFromUri("PATH_OR_URL")
