### ISSUE TITLE
IOS not building since iOS-Client-SDK newest version came out

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#104]
Hi, The new version of IOS-Client-SDK breaks our IOS app. The ziggeo package version is 1.6.11, I tried to upgrade to 1.6.15, but that does not fix the issue.

Here's a screenshot of the build error:
![Screen Shot 2022-08-15 at 12 42 02 PM](https://user-images.githubusercontent.com/44783494/184678947-f944e045-daa4-40e4-acd0-50042b2dd370.png)

**Comment by Bane-D** [comment]
Hi Sam,

Thank you for reporting this.

We are making a new update that should address this. The update is planned to be available before the end of this week.
