### ISSUE TITLE
Use API instead of Ziggeo SDK

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#113]
Hi, I have a quick question regarding the API, I was wondering if it's possible to upload a mp4 file manually using the API. We want to use a single package (in our case we are using react-native-vision-camera) for all the places we use the camera.

This would helps us since we would not have to depend on this package and it would stop preventing us from releasing when there's an update on the pods or on this package. Right now, for some reason for every release push to iOS-Client-SDK it breaks our release and we have to wait until there's a fix on this package to release our app. This is not supposed to happen and it's the only package out of the 80 packages we use that has this problem. Right now our feature using this package has been down for the last 2-3 months and our client are becoming angry.

**Comment by Bane-D** [comment]
Hi Sam, I am sorry to hear about the experience and would be happy to help.

Our API is available through 2 different APIs actually. One is the client side API and would be the recommended one for the mobile devices and the other one is server side (ideally something you would use on your own server and then have your own app communicate with the server to get or set something).

The client side API is ideal if you want to call things from the mobile app side and have them do something on your Ziggeo account, however it also has some limitations compared to server side one.

Server side API on the other hand offers you much more options (even creating auth tokens and retrieving stats), however as it requires both APP Token and Private Key (if auth is used, then encryption token as well) it must not be used on the mobile side, it has to be on your own server. Benefit is however that all calls would be made from your app to your server which in turn communicates with the Ziggeo servers. You would basically have more control over the endpoints used in your mobile app and on your server.

You can of course utilize both.

Now if you would record videos and audios without the use of our mobile SDK it might be best if you use the server side SDK, submit it all to your servers and then go from there.

If you do not want to use your servers or you prefer to use our API directly from the mobile app, then this would be possible by utilizing the API for uploads only.

Please let me know if this seems aligned with what you wanted to achieve or if you wanted to have more features of our SDK in use by your app. Also do let us know which one of the APIs seem like the best option to you.

@katolykdev can you please check the above and see what we might need to do in future to avoid the same.

**Comment by katolykdev** [comment]
Hi Sam. Sorry to hear about the experience and would be happy to help.
It's possible to upload a mp4 file manually using the API. 
You can only use a single package (react-native-vision-camera) for all the places you use the camera to get mp4 file from recorder.
And then you can use your own API to upload a mp4 file manually.
Please let me know if you need more questions.

**Comment by sam-houle1** [comment]
Thanks @katolykdev and @Bane-D for the answer, I will look into that !
