### ISSUE TITLE
video quality should be configurable for android

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [Ziggeo/ReactNativeSDK#12]
Video's for android are uploaded in the highest quality (by default).
On my device this leads to immense upload sizes for short videos.

The upload quality should be configurable.

In the Android SDK it can be set according to https://github.com/Ziggeo/Android-Client-SDK
```
ziggeo.setPreferredQuality(videoQuality);
```

but there is no method in the React Native SDK for this.

**Comment by 3akat** [comment]
Hi @24HOURSMEDIA,
Please take a look at the latest version `1.1.10`.
It is possible via for ex. `Ziggeo.setQuality(Ziggeo.LOW_QUALITY);`

**Comment by 24HOURSMEDIA** [comment]
Thank you. we will look into it in one of our next releases when we update the sdk and library.

**Comment by 3akat** [comment]
Closing the issue, please reopen if you will need any help.
