### ISSUE TITLE
videos are uploaded upside down on LG android device

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [Ziggeo/ReactNativeSDK#13]
On my android LG K8 4G device, videos are uploaded upside down
(I used the front camera position).

**Comment by 3akat** [comment]
Hi,
We already have a fix for native SDK, will be included in react native asap.

**Comment by 3akat** [comment]
Hi @24HOURSMEDIA,
Please, take a look at the latest version `1.1.10`
