### ISSUE TITLE
add tags and custom data to recorded video

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [Ziggeo/ReactNativeSDK#14]
How can I add tags and custom data to videos uploaded from the React Native SDK?

**Comment by 3akat** [comment]
Hi @24HOURSMEDIA,
Please, take a look at the latest version. It is possible via for ex. `Ziggeo.setExtraArgsForRecorder({'tags': 'Some tag'})`

**Comment by 24HOURSMEDIA** [comment]
Thank you. we will look into it in one of our next releases.

**Comment by 3akat** [comment]
@24HOURSMEDIA 
so, I will close the issue, please reopen if you will need any help.
