### ISSUE TITLE
add custom data and tags to locally uploaded videos

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [Ziggeo/ReactNativeSDK#16]
Hi, we are also using
Ziggeo.uploadFromPath

to upload local videos that are recorded from other sources.
Is it possible to set customData and tags to these video's?

Thanks in advance.

**Comment by 3akat** [comment]
Hi @24HOURSMEDIA,
Will be implemented in the next release.

**Comment by 24HOURSMEDIA** [comment]
That's great! Thanks!
