### ISSUE TITLE
Update Package (Build Fail - iOS)

### ISSUE THREAD

**Issue by Saad-Bashar** [Ziggeo/ReactNativeSDK#17]
When I try to update ziggeo-package to latest version 1.2.0. I get few errors which cause the xcode build fail. I guess this happens because of the new fixes and features added to the package. please refer to the following screenshots.

![screen shot 2018-08-08 at 5 51 51 pm](https://user-images.githubusercontent.com/13269141/43830442-d1f068ee-9b33-11e8-9efa-f50023c6545f.png)

and when I try to uncomment that else block. It creates new error with quality feature that has been created 7days ago I suppose. 

![screen shot 2018-08-08 at 5 56 02 pm](https://user-images.githubusercontent.com/13269141/43830649-66922d34-9b34-11e8-826e-9edbd14b835d.png)

Please guide in details how should we upgrade the package. Thanks :)
.

**Comment by alexyats** [comment]
Hi Saad, I think you have to update `Ziggeo.framework` which is linked to your project. You can take it from `iOS-Client-SDK` repository at `Ziggeo/Output/` directory. Please let us know if you will need any further assistance

**Comment by Saad-Bashar** [comment]
Which folder should I choose in output -  **Release-Universal** or just **Release**?

**Comment by Saad-Bashar** [comment]
Okay I used release-universal, it solved the build error.

**Comment by alexyats** [comment]
use `release-universal` for debugging on simulator and real device and `release` for app store build
