### ISSUE TITLE
Video in android cannot adjust volume using sound icon on video

### ISSUE THREAD

**Issue by MrHazimAli** [Ziggeo/ReactNativeSDK#19]
Hye,
I would like to know whether adjust volume using sound icon on the video is possible in android devices? as I tested it's not working.. only in Ios it does work.

Thanks!

**Comment by 3akat** [comment]
Hi @MrHazimAli,
The sound icon was implemented for muting/unmuting the sound. Do you mean this is not working or do you want to change the volume level with the icon?

**Comment by MrHazimAli** [comment]
hi @3akat , the muting/unmuting is working.  👍 just want to know whether it's possible also to change volume level with the icon ?

**Comment by 3akat** [comment]
@MrHazimAli currently it is not possible. We will discuss it today with a team. Will back to you with the estimation.

**Comment by MrHazimAli** [comment]
alright @3akat , thanks a lot! you guys are awesome 👍 💯

**Comment by 3akat** [comment]
@MrHazimAli we will release the feature on the next week

**Comment by MrHazimAli** [comment]
awesome! thanks @3akat 👍
