### ISSUE TITLE
Can't upload videos after updating to new version

### ISSUE THREAD

**Issue by WPShuvo** [Ziggeo/ReactNativeSDK#21]
Hi,
I can't upload any video on any platform after updating to version 1.3.0. 
Do I need to make any changes in code to upload videos in new version?
React-Native v0.47.2

**Comment by 3akat** [comment]
Hi @WPShuvo,
Where do you face the issue on Android or on iOs?

**Comment by WPShuvo** [comment]
Hi @3akat,
I'm facing this issue on both platforms.

**Comment by alexyats** [comment]
@WPShuvo could you please update react-native to 0.55.4 and try it again?

**Comment by 3akat** [comment]
Обеде н в два море кур hrjhy h3ewjwrwjl

пт, 28 сент. 2018 г., 13:01 Alexey Yatsura <notifications@github.com>:14,60
B91 ruo
SwiftKeyt, r. Opera zx,

**Comment by alexyats** [comment]
@WPShuvo do you still facing the issues or should we close the issue?
