### ISSUE TITLE
Please support useLiveStreaming setting for streaming recording

### ISSUE THREAD

**Issue by joelgetaction** [Ziggeo/ReactNativeSDK#27]
Hi,

I notice that in your [iOS SDK](https://ziggeo.com/docs/sdks/mobile/ios) you support streaming recording:
```
Streaming Recording
    recorder.useLiveStreaming = YES;

Streaming recording mode will upload the video stream during the recording without caching to local file first. Video preview and video re-record are not available in this mode.
```
However your [Android SDK](https://ziggeo.com/docs/sdks/mobile/android) makes no mention of this `useLiveStreaming` setting, nor does your RN SDK.

So is `useLiveStreaming` support on all three platforms: iOS Native, Android Native and React Native?

If not, is there a technical reason or can I help with a PR?

We need `useLiveStreaming` because if our users record a long video, we don't want to upload the recording once they're done but rather while they're recording so that as soon as they're done they can leave our app.

Thanks!

**Comment by 3akat** [comment]
Hi! 
Currently streaming is not implemented in Android and as a consequence, there is no streaming in cross-platform SDKs, but this is in the nearest backlog. 
Soon we will publish a new version of RN SDK, where uploading will be completely in the background, so the user will be able to submit the video and leave the app.

**Comment by bybash** [comment]
HI @3akat according to your latest message I know it has been a while but does your latest version support `where uploading will be completely in the background, so the user will be able to submit the video and leave the app` now?

**Comment by 3akat** [comment]
Hi @bybash.
The question is more about the android system, not the streaming. It's not possible to upload video completely in the background in android, this is forbidden by the system, you must show notification for background process.  
If you're talking about streaming video to the server during recording process - it has been implemented for native part, so it's also now possible to add in React Native SDK.  
Will put it in my nearest plan.
