### ISSUE TITLE
How can I create custom UI for your recorder or overlay my own views on top of your recorder?

### ISSUE THREAD

**Issue by joelgetaction** [Ziggeo/ReactNativeSDK#28]
Hi,

Thanks for making this awesome SDK available!  :-)

I would like to do two things with your RN SDK:
1. Alter your recording controls or create my own to match the look and feel of my app (e.g. button shapes, fonts, colors, etc.)
2. Overlay a transparent drawing canvas on top of the recorder so that the user can draw shapes (e.g. lines) to highlight certain areas of the videos.  I record the timestamp of these and send these drawn shapes to my own server and then time sync them with the recorded video later during playback.

I don't see how to do 1.

I don't think 2 is possible the way you're currently running your recorder because [here](https://github.com/Ziggeo/ReactNativeSDK/blob/master/ios/RCTZiggeoRecorder.m#L233) you present your recorder as a full screen `UIViewController` which is going to cover the root view controller that's presenting the RN views.

So how can I overlay RN views on *top* of your Ziggeo recorder?  And how can I control the sizing of your ziggeo recorder, if I don't want it to be full screen?

Thanks!

**Comment by alexyats** [comment]
Hi, we are working on both features right now, and will include these features into the next release

**Comment by joelgetaction** [comment]
@alexyats thanks for responding so quickly!  Just to give me an idea, are you planning to allow your recorder to be presented in React Native UI as a view so I can mix it into the view hierarchy of my RN app with the rest of my RN views?

Is there any way I can help beta test this to get an early peak at it ... :-)

**Comment by 3akat** [comment]
Hi! Yup, we will wrap native view component in RN staff to allow you to use camera view as a simple react native view. 
Regarding beta testing - we have fast development process, so as soon we will finish the implementation everything will be tested and released in a day or two :)

**Comment by joelgetaction** [comment]
Thanks @3akat , that's awesome news!  :-). Much appreciated!

**Comment by r888888888** [comment]
Are there any updates on the progress of this? Customization of the recorder UI is a feature we would love to have access to.

**Comment by ntshrocha** [comment]
HI @r888888888, my colleagues want to be sure the customization works right on all different devices and as such this has been placed on our roadmap until a few other features are improved upon. We'll be happy to keep you updated, I also strongly suggest starring or following the repository to get notifications on all updates as they happen. :)

**Comment by isatanis** [comment]
Hey guys, I'm waiting for this feature. Are you working on it? What's the release plan? Thanks.

**Comment by bybash** [comment]
Hey guys, is there any news? Or any development branch which we can contribute.

**Comment by fatihcandev** [comment]
> Hey guys, is there any news? Or any development branch which we can contribute.

+1

**Comment by 3akat** [comment]
Hey guys!
We did a beta version, please take a look and tell if it works for you or do we need to add something more specific
https://github.com/Ziggeo/ReactNativeDemo/tree/new_demo_custom_recorder

**Comment by fatihcandev** [comment]
> Hey guys!
> We did a beta version, please take a look and tell if it works for you or do we need to add something more specific
> https://github.com/Ziggeo/ReactNativeDemo/tree/new_demo_custom_recorder

@3akat Thanks a lot! I tried it out yesterday and works like a charm 👍🏼  One thing though. I made some research in the module but couldn't see any method to get the current camera type (front / back) or trigger the change. It'd be great if you could share a way to get that done 🙏🏼

**Comment by 3akat** [comment]
Hi @fatihcandev!
Regarding camera type - will add 👌 
Regarding import in ts project - if it throws the error how did you start it?

**Comment by fatihcandev** [comment]
> Hi @fatihcandev!
> Regarding camera type - will add 👌
> Regarding import in ts project - if it throws the error how did you start it?

Hi @3akat! I worked on the branch you shared.

**Comment by 3akat** [comment]
That is because the feature still in demo version and has not been released. Also currently this exists only for android, iOs is under development.
Since you're telling everything is fine we'll start with iOs part.

**Comment by fatihcandev** [comment]
> That is because the feature still in demo version and has not been released. Also currently this exists only for android, iOs is under development.
> Since you're telling everything is fine we'll start with iOs part.

Thanks! I've only worked on customizing the camera view but I'll try other core features as well and get back to you.

**Comment by 3akat** [comment]
@fatihcandev do you plan to do releases for both iOs and Android?

**Comment by bybash** [comment]
> @fatihcandev do you plan to do releases for both iOs and Android?

Hey, @3akat we're working on the same project with @fatihcandev and we're planning to release it for all android and iOS. We don't want to find some other workarounds for background uploading for iOS. We've been using Ziggeo for our web application and we want to keep it aligned on mobile platforms. So if you can share an estimated plan for this feature release, we'd be very appreciated. 
Thank you.

**Comment by 3akat** [comment]
Hi @bybash,
Roger that, will discuss this internally.

**Comment by bybash** [comment]
> Hi @bybash,
> Roger that, will discuss this internally.

Thank you 🙏

**Comment by 3akat** [comment]
Hi @fatihcandev, I realized that we actually already have a setting for switching camera to front/back. It is the `facing` property   
```
<ZiggeoCameraView
            facing={this.state.facing}
...
```
Please, try using 0 for back and 1 for front.

**Comment by bybash** [comment]
> Hi @bybash,
> Roger that, will discuss this internally.

Hey @3akat are there any news?
Regards,
Hakan

**Comment by 3akat** [comment]
Hi @bybash, just got a response for our iOs team - the component for iOs will be ready at the end of the next week

**Comment by bybash** [comment]
> Hi @bybash, just got a response for our iOs team - the component for iOs will be ready at the end of the next week

@3akat thanks for the great news, looking forward to getting our hands dirty. 
Thanks for your and all the team's efforts.

**Comment by bybash** [comment]
Hey @3akat, any news? We're excited to use it :-)

**Comment by 3akat** [comment]
Hey @bybash! We're clearing up things for iOs and doing our best to share the beta with you ASAP.

**Comment by bybash** [comment]
hey @3akat it's been a while so I'd like to ask again :-) Is there any news?

**Comment by 3akat** [comment]
Hi @bybash! Please take a look at version `1.4.36`.  
Note: `facing`(int) renamed to `camerafacefront`(bool) to be consistent with JS SDK

**Comment by 3akat** [comment]
Closing it due to inactivity, please create a new issue if you need something else.
