### ISSUE TITLE
UploadFromFile and Record don't return token

### ISSUE THREAD

**Issue by diesmori** [Ziggeo/ReactNativeSDK#29]
Weeks later, I got video tokens when they were uploaded. But now, they just upload.
These token were returned at version 1.3.8, but later I updated to 1.3.9 to solve [this issue](https://github.com/Ziggeo/ReactNativeSDK/issues/26).

I tried with que example project too, old branches of my project and still have no tokens.

Thank you in advance.

**Comment by 3akat** [comment]
Hi @diesmori! Will take a look.

**Comment by 3akat** [comment]
Hey @diesmori, please take a look at the version `1.3.10`

**Comment by diesmori** [comment]
Now it's working fine! Thanks a lot.

Is there someting like a token listener? Similar to "UploadProgress" but to know from every component  when the video is ready and returned its token.

**Comment by 3akat** [comment]
No, there is no such. We can add the event, but I think this is unnecessary, because you can do anything you want with the token after await executes.
@alexyats 
Alex, what do you think?

**Comment by 3akat** [comment]
Closing since it's not relevant anymore. Feel free to reopen if you still missing some functionality in the latest version.
