### ISSUE TITLE
Usage with Expo

### ISSUE THREAD

**Issue by guilhermesad** [Ziggeo/ReactNativeSDK#30]
Hi there!

I would like to use the Ziggeo React Native SDK with expo: https://expo.io. I see we need to change some specific android/ios files when using the Ziggeo SDK. How would that work with Expo?

Thanks!

**Comment by 3akat** [comment]
Hi @guilhermesad! Will take a look

**Comment by guilhermesad** [comment]
@3akat thanks

**Comment by 3akat** [comment]
@guilhermesad 
In short: works fine, just follow the README section :)

I've tried our SDK (tested on Android) with Expo in the following way
 - installed Expo, created and started HelloWorld app
 - installed Ziggeo SDK with the commands from `Automatic Installation`
 - followed steps `2`, and `6`
 - copied content from `App.js` from the demo `https://github.com/Ziggeo/ReactNativeDemo` to the Expo HelloWorld app

So, please try it out, I would be happy to help with any issues on Android side and @alexyats will help with iOs.

**Comment by guilhermesad** [comment]
thanks @3akat! How do you do steps `2` and `6` though, if Expo doesn't have an `android/` folder?

**Comment by 3akat** [comment]
Here is the sample I've tried  
https://docs.expo.io/versions/latest/bare/hello-world/  
after executing the `expo init --template bare-minimum` I have the following structure  
![image](https://user-images.githubusercontent.com/2178533/57507217-ce522a00-7306-11e9-94ac-72d9df4c3b12.png)   
So, there is an `android` folder. Is it possible we're talking about different frameworks?

**Comment by guilhermesad** [comment]
thanks @3akat. I was wondering though about the standard installation, not the `bare-minimum` one. Unless there's a way to take advantages of the expo features on the `bare-minimum` mode? For example, how would you build a standalone app [the expo way](https://docs.expo.io/versions/v32.0.0/distribution/building-standalone-apps/)? Just setting `app.json` correctly and running `expo build:android` doesn't seem to work.

**Comment by 3akat** [comment]
Hi @guilhermesad,
I've played a little bit with the Expo, in short: you have to use the `bare` mode or follow the **Detaching to ExpoKit** way  
https://docs.expo.io/versions/v28.0.0/expokit/detach/

**Comment by guilhermesad** [comment]
ok, thanks. Any plans in providing a full-compatible with expo version?

**Comment by 3akat** [comment]
Hi @guilhermesad, 
We estimate the time required for development, as soon as we finish I’ll let you know.

**Comment by guilhermesad** [comment]
ok thanks!

**Comment by fractalmarc** [comment]
bump, any info on the estimated time for dev on this? I want to use ziggeo with a production Expo app that would really suffer from having to be ejected. I may have bandwidth to contribute to making ziggeo fully compatible with expo, and would like to know the estimate of this work's difficulty + any existing progress before I break ground.

**Comment by 3akat** [comment]
Hi @fractalmarc,
Unfortunately, we don't have time right now for developing Expo SDK.
If you will be able to contribute that'd be awesome!
Here are a few links that may be useful
https://ziggeo.com/docs/sdks/javascript
https://www.npmjs.com/package/expo-camera
Please don't hesitate to ask me if you need some additional info.

**Comment by 3akat** [comment]
Hi @fractalmarc, hope you are doing well!
Did you have a chance to try to implement ziggeo + expo application for your needs?
