### ISSUE TITLE
Ziggeo.h not found at ios/RCTZiggeoRecorder.h

### ISSUE THREAD

**Issue by diesmori** [Ziggeo/ReactNativeSDK#31]
I'm trying to deploy an iOS app, following all the instructions, readme files and old issues, also checked the example app and it builds perfectly.

When I try to build (to an emulator), I get this error message:

> (...)/node_modules/react-native-ziggeo-library/ios/RCTZiggeoRecorder.h:12:9: fatal error: 'Ziggeo/Ziggeo.h' file not found
#import <Ziggeo/Ziggeo.h>

I think there's a route mismatch, IDK really. Please help me, I'm finally deploying!

**Comment by alexyats** [comment]
Hi, it seems you don't have Ziggeo objective-C SDK installed. Please ensure you have downloaded Ziggeo.framework from here: `https://github.com/Ziggeo/iOS-Client-SDK/tree/master/Ziggeo/Output/`and installed it in your app
