### ISSUE TITLE
Unhandled JS Exception: TypeError: null is not an object (evaluating 'ZiggeoRecorder.rearCamera')

### ISSUE THREAD

**Issue by xbrowserapp** [Ziggeo/ReactNativeSDK#35]
I setup a new React Native project and then followed the steps for iOS setup exactly as described in the README. As soon as I imported Ziggeo I got this error. None of the other problem threads like this one are applicable to my app since I am not using expo. 
<img width="276" alt="Screen Shot 2019-10-15 at 10 53 59 AM" src="https://user-images.githubusercontent.com/50834000/66852418-2a664d80-ef3a-11e9-9836-88a4cd6ab6fa.png">

**Comment by alexyats** [comment]
please check our demo project here `https://github.com/Ziggeo/ReactNativeDemo`
do you have the same error running it?

**Comment by xbrowserapp** [comment]
I cloned the project and then ran it after doing an npm install, here is the error I got when trying to run through xcode: 
<img width="274" alt="Screen Shot 2019-10-15 at 12 27 51 PM" src="https://user-images.githubusercontent.com/50834000/66858866-66ec7600-ef47-11e9-8092-0f61d63079d7.png">

**Comment by xbrowserapp** [comment]
Here is the full error
<img width="878" alt="Screen Shot 2019-10-15 at 12 48 45 PM" src="https://user-images.githubusercontent.com/50834000/66860333-36f2a200-ef4a-11e9-8c1c-2d07115fdafa.png">
