### ISSUE TITLE
Support for iOS on versions 0.61.0 and up

### ISSUE THREAD

**Issue by yaronlevi** [Ziggeo/ReactNativeSDK#36]
Hi (-:

We are trying to integrate the SDK with our app. On Android, everything went smoothly.
On iOS, however, we get an error when running the app:

`null is not an object evaluating ZiggeoRecorder.rearCamera`

Our app is built with RN version 0.61.5.
When we tried setting our RN version to 0.59.0, suddenly it worked fine. But unfortunately, we can't go live with this lower version. It's a real deal-breaker for us.

Is there any solution on the horizon, or in the meanwhile some quick workaround?

Thanks for any help on the issue.

**Comment by alexyats** [comment]
Hi, thanks for letting us know about the issue, we will try to resolve the issue by the end of the week

**Comment by Bane-D** [comment]
Hi Yaron, no need to mention anything on #35 as per my earlier comment on a different thread since you have a new issue opened here. Mentioning the previously reported one (#35) here as well so that we have them connected.

Thank you

**Comment by yaronlevi** [comment]
For your convenience, I've created a [clean repo](https://github.com/yaronlevi/ziggeo_test) that reproduces the bug.

**Comment by yaronlevi** [comment]
Hi (-:
Any progress on the issue?

**Comment by 3akat** [comment]
Hi @yaronlevi, sorry for delay!
I'm from Android side but will do my best to help with the issue.

**Comment by yaronlevi** [comment]
@3akat Hi, anything else I can provide you to help solve the issue?

**Comment by alexyats** [comment]
@yaronlevi sorry for delay, it is taking more than expected, but we will finish it in a few days

**Comment by yaronlevi** [comment]
I see that 1.4.3 is out. Does it solve the issue by any chance?

**Comment by 3akat** [comment]
not yet unfortunately, but we're trying to understand what's going on at this moment

**Comment by yaronlevi** [comment]
@3akat Have you tried to run the repo I've made above? It can easily reproduce the problem...

**Comment by 3akat** [comment]
@yaronlevi yup, I can reproduce it from your repo, but I don't get why this is happening. Seems like wrong library linking somewhere

**Comment by alexyats** [comment]
@yaronlevi please add these lines to `iOS/Podfile` and run `pod install`:
```
  pod 'ZiggeoRN', :git => 'https://github.com/Ziggeo/ReactNativeSDK.git'
  pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'
```
it should resolve the issue

**Comment by yaronlevi** [comment]
I've added the lines in the [clean repo](https://github.com/yaronlevi/ziggeo_test), did "pod install" but now I am getting this error when running:
<img width="1463" alt="Screen Shot 2020-04-06 at 11 59 51" src="https://user-images.githubusercontent.com/5398977/78541349-2b4bae00-77fe-11ea-9992-e3ac32cb13a6.png">

**Comment by alexyats** [comment]
This is known issue of new Xcode build system. Try to clean build and use legacy build system in workspace settings

**Comment by yaronlevi** [comment]
Are you sure? maybe it's happening because of step 3 in the docs (which is not needed anymore since we've added the two lines in the pod file)
<img width="1035" alt="Screen Shot 2020-04-06 at 12 32 31" src="https://user-images.githubusercontent.com/5398977/78544472-dc544780-7802-11ea-86bd-f180e3a30bc5.png">

**Comment by alexyats** [comment]
You are right, this step is not needed anymore, docs are updated

**Comment by yaronlevi** [comment]
I think we should also make a change under the docs [here](https://ziggeo.com/docs/sdks/mobile/react-native). Thank you for the help!
