### ISSUE TITLE
No RecordingStopped Event in iOS 

### ISSUE THREAD

**Issue by yaronlevi** [Ziggeo/ReactNativeSDK#37]
Hi (-:

Our users record long videos, about 20-30 min. When the user finished a recording, we want to show him a popup that says "The video recording is complete. Now your video will be uploaded in the background. Youll be notified when it's finished".

We used the following code to hook up to the event of video recording stopped:
```
const subScribeToEndRecord = recorderEmitter.addListener(
    'RecordingStopped',
    onRecordEnd,
  );
```

This works fine on Android but on iOS we get:

![IMG_20200406_214416](https://user-images.githubusercontent.com/5398977/78595850-64fad400-7853-11ea-8d0b-247399d49600.jpg)

How can we get notified in iOS when the video recording has finished?

**Comment by katolykdev** [comment]
Fixed in 1.4.15.
