### ISSUE TITLE
Exiting app while on record screen causes the app to stuck

### ISSUE THREAD

**Issue by yaronlevi** [Ziggeo/ReactNativeSDK#39]
Hi (-:

I hope you are feeling well.

Happens on Android.

[Repo](https://github.com/yaronlevi/ziggeo_ios_record_fail) with the bug.

After starting a new recording by calling `await Ziggeo.record();`, if you try to move the app to the background (for example by going to the home of your phone) when you come back to the app, it's now stuck you can only get out of this state by force closing the app.

Step 1 - open the record screen (you don't have to start a new recording)

![Screenshot_20200416-223642](https://user-images.githubusercontent.com/5398977/79500724-96368980-8035-11ea-9c74-b72ab6f00951.png)

Step 2 - Press the home button of the phone and then open the app again. Now you'll see a black screen and the app is stuck. It sometimes also happens when you lock the phone and unlock it.

![Screenshot_20200416-223550](https://user-images.githubusercontent.com/5398977/79500825-c54cfb00-8035-11ea-99b1-84c4c6a14b93.png)

**Comment by 3akat** [comment]
Hi @yaronlevi, thanks for reporting!
Will review soon.

**Comment by 3akat** [comment]
I have resolved the issue, will publish with several other improvements at the end of the next week.

**Comment by yaronlevi** [comment]
@3akat hi, is there a way we can get the fix before the end of the week by any chance?

**Comment by 3akat** [comment]
Hi @yaronlevi!
I have pushed version `1.4.6`, please take a look :)

**Comment by yaronlevi** [comment]
@3akat Do we need a new native build or updating the package.json to 1.4.6 and doing npm install is enough?

**Comment by 3akat** [comment]
@yaronlevi you need only to run `npm install` and do a clean build

**Comment by yaronlevi** [comment]
Thank you! issue resolved.
