### ISSUE TITLE
uploadFromPath throwing unknown error

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#59]
I was trying out this feature with a combination of [react-native-camera (**rnc**)](https://www.npmjs.com/package/react-native-camera) and [react-native-document-picker (**rndp**)](https://www.npmjs.com/package/react-native-document-picker) and it does not work.

When I record with **rnc** I get a response with the file's uri where it is stored. To make sure this file was in fact a working video, I tried [react-native-video](https://www.npmjs.com/package/react-native-video) and everything played as expected. But sending through uploadFromPath throws an error. (see below)

I tried using a file picker, **rndp**, in-case this has to do with the type of file **rnc** made. But it still did not work. The parameter name is "fileName" which maybe would mean it doesn't want a uri but the actual fileName. So I passed the fileName instead of the uri from the file picker and it still didn't work.

Lastly, I though, maybe it can't load the file for some reason, so I event tried converting the fileURI to a base64 representation of the video file. Still did not work.

Dependencies:
```
"react": "17.0.1",
"react-native": "^0.64.2",
"react-native-camera": "^3.44.3",
"react-native-fs": "^2.16.6", // For base64 encoding
"react-native-document-picker": "^5.2.0"
"react-native-ziggeo-library": "^1.4.35", // Tried everything 1.4.31 >=
```

Code sample
```
    send = async fileURI => {
        Ziggeo.setAppToken(ZIGGEO_APP_TOKEN);
        const recorderEmitter = Ziggeo.recorderEmitter();
        this.watchEmitter(recorderEmitter);

        try {
            const token = await Ziggeo.uploadFromPath(fileURI, {
                // tags: 'dsdsd',
                // expiration_days: 1,
                // video_profile: '_video_profile_lightweight',
                // auto_pad: true,
                // data: '{"source":"app"}',
            });

            if (token) {
                Ziggeo.play(token);
            }

            this.setState({ token }, this.onTokenUpdated);
        } catch (error) {
            console.error(error);
            await this.delete();
        }
    }
```

**console.error log**
ios: `[Error: unknown recorder error]`
android: `[Error: ${fileURI}]`

**Comment by 3akat** [comment]
Hi @jessypouliot98, thanks for reporting, we will look into this.

**Comment by 3akat** [comment]
@jessypouliot98 v`1.5.0` should contain fix for Android, please take a look. iOs will come later

**Comment by jessypouliot98** [comment]
@3akat We don't have the code anymore to try it out.

We tried to use this as a fallback to another problem we encountered, but we made a "sketchy", temporary, bypass to the original problem (the one with the modal). That said, we might use this in the future but we will not be using this feature at the moment.

**Comment by katolykdev** [comment]
@jessypouliot98 Before you use the url, you have to remove "file://" on the url.
const filePath = data.uri.replace("file://", "");


// react-native-camera (rnc)
const data = await promise;
const filePath = data.uri.replace("file://", "");
this.uploadFile(filePath);

// react-native-document-picker (rndp)
const res = await DocumentPicker.pick({
      type: [DocumentPicker.types.video],
});
let filePath = res.uri.replace("file://", "");
this.uploadFile(filePath);

**Comment by 3akat** [comment]
Closing the issue. Please reopen if the error still exists.
