### ISSUE TITLE
Add official support for latest react-native version

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#60]
When trying to install the package I need to use the `--force` or `--legacy-peer-deps` flag to install it.

I am currently on:
```
"react": "17.0.1",
"react-native": "^0.64.2",
```

**Comment by 3akat** [comment]
Hi @jessypouliot98, thanks for the request. 
I'll add this task to the backlog and hope to finish it during one of the nearest sprints.

**Comment by 3akat** [comment]
Please take a look at v`1.5.0`

**Comment by jessypouliot98** [comment]
@3akat unfortunately, like most other releases, there are [problems with the build with iOS](https://github.com/Ziggeo/ReactNativeSDK/issues/65) making it unusable. Though, this does actually fix the npm error
