### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#61]
The lastests version of the package are having difficulties installing on iOS.

I am currently trying to install the lastest version as of today (`1.4.3-6.pf1`)

![Screen Shot 2021-07-22 at 10 42 33 AM](https://user-images.githubusercontent.com/35693647/126658618-fae9863c-b3ed-408f-866a-7fbf2769b5ab.png)

This also happens with `1.4.36`.

The versions I was able to install are `1.4.31` and `1.4.35`

-------------------------------

Also for the Podfile the following is not working
```
  pod 'ZiggeoRN', :git => 'https://github.com/Ziggeo/ReactNativeSDK.git'
  pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'
```
But this fixes the installation of pods
```
  pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'
```

Since ZiggeoRN come with the npm package, it gets auto added to pods by react-native. 

Here is an error thrown by `pod install`
```
[!] There are multiple dependencies with different sources for `ZiggeoRN` in `Podfile`:

- ZiggeoRN (from `../node_modules/react-native-ziggeo-library`)
- ZiggeoRN (from `https://github.com/Ziggeo/ReactNativeSDK.git`)
```

**Comment by katolykdev** [comment]
@jessypouliot98  You can check this one. https://github.com/Ziggeo/ReactNativeSDK/issues/65#issuecomment-894280553

**Comment by katolykdev** [comment]
@jessypouliot98 This is also resolved. right? If yes, we will close this issue.

**Comment by jessypouliot98** [comment]
@katolykdev I mean, the problem is still inside the package, it is not resolved until a fix is released ?

**Comment by katolykdev** [comment]
@jessypouliot98 Did you test it via 1.5.0?

**Comment by jessypouliot98** [comment]
@katolykdev actually, you can close this one, it's not the same error, but the other one that was closed is a problem with the current 1.5.0.

Readme is still wrong though

**Comment by katolykdev** [comment]
Yes. we will update the Readme file. So you won't have any problem with latest Readme file.

**Comment by katolykdev** [comment]
@jessypouliot98 About ZiggeoRecorder2, it was deleted on new version(1.5.0).
Please update the version of react-native-ziggeo-library on package.json file.
"react-native-ziggeo-library": "^1.5.0",
