### ISSUE TITLE
Unable to build iOS with version 1.5.0

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#65]
I have got this error in the past with another release(s), can't remember which one (maybe 1.4.33 ?)

Here is the "detailed" error from Xcode
![Screen Shot 2021-08-05 at 1 56 22 PM](https://user-images.githubusercontent.com/35693647/128398673-918a5a8a-547f-42c7-961a-c2d0d27760fc.png)
![Screen Shot 2021-08-05 at 1 56 33 PM](https://user-images.githubusercontent.com/35693647/128398680-a4159c58-e83b-4338-84c6-6717626520ad.png)

package.json
```
"react": "17.0.1",
"react-native": "^0.64.2",
"react-native-ziggeo-library": "^1.5.0",
```

Podfile
```
pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'
```

PS: "pod 'ZiggeoRN', :git => 'https://github.com/Ziggeo/ReactNativeSDK.git'" is not used as it causes another [error](https://github.com/Ziggeo/ReactNativeSDK/issues/61).

**Comment by jessypouliot98** [comment]
I have tried
```
$ cd ios
$ rm -rf build
$ xcodebuild clean
```

`pod install --repo-update`

tried reinstalling everything also

----------------

Everything looks fine on android

**Comment by katolykdev** [comment]
@jessypouliot98 
ZiggeoRN was already added in package.json.
You don't need to add below code in Podfile.
pod 'ZiggeoRN', :git => 'https://github.com/Ziggeo/ReactNativeSDK.ZiggeoRN'

Please remove it.  We will update readme file for iOS build soon.

![1](https://user-images.githubusercontent.com/64797925/128521599-12e1dc26-611e-4875-b657-b213a9255924.png)
![2](https://user-images.githubusercontent.com/64797925/128521613-1d6a2447-477f-42a7-9ca5-e019d1c1d207.png)
![3](https://user-images.githubusercontent.com/64797925/128521627-0e313f1f-0a8b-456b-a466-6c1789313682.png)

**Comment by jessypouliot98** [comment]
@katolykdev as described, I already do not have it in my Podfile, I was just referencing it to remind that either the documentation is wrong or something else was wrong. I was able to build with other prior versions, some needed a bit of changes (on 1.4.35, ZiggeoRecorder2 error had to be renamed to ZiggeoRecorder) but this version, 1.5.0, nothing was found on my end to make it work.

This is why I opened the issue.

Package.json
"react-native-ziggeo-library": "^1.5.0",

Podfile.lock
- iOS-Client-SDK (from `https://github.com/Ziggeo/iOS-Client-SDK.git`)
- ZiggeoRN (from `../node_modules/react-native-ziggeo-library`)

**Comment by jessypouliot98** [comment]
@katolykdev Update, I actually just found the fix..

![Screen Shot 2021-08-06 at 10 41 14 AM](https://user-images.githubusercontent.com/35693647/128527728-b9883260-3755-4618-aa15-467dfc9df98b.png)

Add the highlighted line to the package please 🙏

**Comment by katolykdev** [comment]
Great

**Comment by jessypouliot98** [comment]
@katolykdev The problem is still in the package though.. There is a manual fix, but everyone installing the package has to add an import to the file in Xcode
