### ISSUE TITLE
iOS Ziggeo.play not showing

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#69]
react-native-ziggeo-library@1.5.2

This is a bug I found a couple weeks ago and decided to bypass it by using react-native-video to play the video instead of ziggeo itself. (Though react-native-video doesn't work well on Android for our needs so we still use Ziggeo.play on Android)

On v1.4.31 it used to log an error in Xcode, but now it is just invisible (but I do hear the video). I believe the problem from v1.4.xx was fixed, though I still can't view the video with it.

I believe the video might be showing under our modal on iOS, but I can't be sure.

This is a non-issue for us at the moment, but had to log this issue for the # (Nice.)

**Comment by 3akat** [comment]
We did some refactoring, there is now should be a method called `.playVideo()`. Please reopen if you need more help here.
