### ISSUE TITLE
Unhandled JS Exception: The callback record() exists in module ZiggeoRecorder, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by dancomanlive** [Ziggeo/ReactNativeSDK#7]
This happens after a video is uploaded and I click the X button to quit the video recorder.

**Comment by alexyats** [comment]
what platform is affected?

**Comment by dancomanlive** [comment]
ios

**Comment by dancomanlive** [comment]
Anyone there??

**Comment by dancomanlive** [comment]
Look, we are about to become your client so we would very much appreciate if you can provide some support.

**Comment by dancomanlive** [comment]
The problem does not occur anymore, the ui was updated as well so I guess it s fixed. Good job Ziggeo team!
