### ISSUE TITLE
Ziggeo.cancelRequest(); not working

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#70]
We want to prevent uploading and processing when user exits during video upload/processing, but this the cancelRequest function doesnt do anything.

I cancel the request at 50% upload and after a couple of seconds it appears in our dashboard completed.

Expected behavior: After canceling a request, it should NOT appear in dashboard.

`react-native-ziggeo-library: 1.5.2`

android & ios

**Comment by 3akat** [comment]
Should be working in the latest version, please reopen if you need more help here.
