### ISSUE TITLE
Android performance issue during video upload/processing

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#71]
Android 10
Huawei p20
react-native 0.64.2
react 17.0.1
react-native-ziggeo-library 1.5.2
javascript engine: hermes

I noticed this problem when we initialy started the project a couple months ago on 1.4.31. I thought nothing of it really, maybe unoptimized code or something for our progress state / progress bar style.

While trying to test [this issue](https://github.com/Ziggeo/ReactNativeSDK/issues/70) on android, I had to try and fix this performance issue. So I disabled every frequent state change and removed our progress bar from render and the app is still unresponsive.

By unresponsive, I mean that everything that is pressable does not work, a ScrollView does work though. This leaves me to believe that native code works and the javascript thread might be locked somehow. This is only a hypothesis as progress bar re-render does work. Maybe it is unlocked for miliseconds before locking again.

iOS works flawlessly with/without progress bar / progress state update

**Comment by 3akat** [comment]
Hey @jessypouliot98, I can't see any issues. Please reopen if you still have it.
