### ISSUE TITLE
Cannot build iOS with iOS-Client-SDK 1.1.30

### ISSUE THREAD

**Issue by jessypouliot98** [Ziggeo/ReactNativeSDK#75]
**Hey, it's me again..**

pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'

The current latest native code for iOS breaks the package, again...

**Current fix:** 

**Change this:**
`pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'`

**to this:**
`pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :commit => '295f90fc8777ebe63135359e20fa144409d02e54'` (downgrade back to "1.1.29" commit)

I wish the iOS-Client-SDK is not a git dependancy but included INSIDE the package. This will allow auto-linking and remove the need to manually add in Podfile, but most importantly prevent any "random" sudden breaking changes..

**Comment by jessypouliot98** [comment]
"react-native-ziggeo-library": "^1.5.2",

**Comment by bobananto24** [comment]
@jessypouliot98 You are a lifesaver

**Comment by 3akat** [comment]
Closing the issue. 
@jessypouliot98 please reopen if you need some more help here.
