### ISSUE TITLE
Cannot build android

### ISSUE THREAD

**Issue by bobananto24** [Ziggeo/ReactNativeSDK#76]
@oliverfriedmann  I did:
**step1**: npm install react-native-ziggeo-library --save
**step2**: react-native link
**step3**: Open up android/build.gradle
            Insert the following line inside the allprojects/repositories block:
            maven { url 'https://jitpack.io' } 
**This is my configuration:**
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
(I cannot change these versions)
    **The result of "react-native run-android" :** 
    _**Task :react-native-ziggeo-library:compileDebugKotlin FAILED**_

**Comment by bobananto24** [comment]
> Hi @bobananto24, did you try it with a new RN application or with our Demo app?
> If it's new - do you use Expo or is it simple react-native?

@3akat 
I tried it in my React native application that I am working with currently.

**Comment by 3akat** [comment]
@bobananto24 can you please share the content of this file?  
![image](https://user-images.githubusercontent.com/2178533/133887716-0186f346-1f06-4399-8efb-70e34803083c.png)

**Comment by bobananto24** [comment]
> @bobananto24 can you please share the content of this file?
> ![image](https://user-images.githubusercontent.com/2178533/133887716-0186f346-1f06-4399-8efb-70e34803083c.png)

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-all.zip

**Comment by 3akat** [comment]
please take a look at version 1.5.3

**Comment by bobananto24** [comment]
> please take a look at version 1.5.3

@3akat  I have tried now and getting the same error.

**This is what I am getting**
Task :react-native-ziggeo-library:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
233 actionable tasks: 14 executed, 219 up-to-date
e: /Users/boban24/Documents/GitHub/kinky/node_modules/react-native-ziggeo-library/android/src/main/java/com/ziggeo/utils/FileUtils.kt: (461, 32): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ziggeo-library:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by 3akat** [comment]
@bobananto24 pushed v `1.5.4` with the fix for the mentioned error, please try a new one

**Comment by bobananto24** [comment]
> @bobananto24 pushed v `1.5.4` with the fix for the mentioned error, please try a new one

Built successfully with v1.5.4. Thank you @3akat

**Comment by bobananto24** [comment]
Execution failed for task ':react-native-ziggeo-library:compileDebugKotlin'.
> Compilation error. See log for more details
I am facing the same error while building after updating to "react-native-ziggeo-library": "^1.6.1",
