### ISSUE TITLE
Ziggeo.play() crashes the app

### ISSUE THREAD

**Issue by bobananto24** [Ziggeo/ReactNativeSDK#77]
Hello @3akat, Now another issue pops up

```
try {
      //record and upload the video and return its token
      var token = await Ziggeo.record();
      console.log("Token:" + token);
      if (token) {
        Ziggeo.play(token);  // app crashes here
      }
    } catch (e) {
      //recorder error or recording was cancelled by user
      alert(e);
    }
```
    When the Ziggeo.record function finishes it crashes the app.
    (This has happened in an android real device and when tried in an ios simulator nothing has happened at all neither playing nor crashing)

**Comment by 3akat** [comment]
Hi @bobananto24, will take a look

**Comment by 3akat** [comment]
Please take a look at the v`1.5.5`

**Comment by bobananto24** [comment]
> Please take a look at the v`1.5.5`

yes, that was working as expected in android, but when it comes to ios(simulator) I can hear only the audio I couldn't see any visual changes happened in there.

**Comment by jessypouliot98** [comment]
@bobananto24 https://github.com/Ziggeo/ReactNativeSDK/issues/69

You can always bypass the Ziggeo.play() by using the video's url and loading it into a videoplayer

**Comment by bobananto24** [comment]
> @bobananto24 #69 (nice)
> 
> You can always bypass the Ziggeo.play() by using the video's url and loading it into a videoplayer

thanks @jessypouliot98 but how could I get the video URL recorded from ziggeo video recorder

**Comment by jessypouliot98** [comment]
@bobananto24 https://ziggeo.com/docs/sdks/javascript/api

You can use any video player and pass the video url which is documented in Url Structure section

**Comment by 3akat** [comment]
Hi @bobananto24, do you need any more help here?

**Comment by bobananto24** [comment]
> Hi @bobananto24, do you need any more help here?

Everything seems fine now, thanks @3akat
