### ISSUE TITLE
Add new ZiggeoPackage() to the list returned by the getPackages() method

### ISSUE THREAD

**Issue by dancomanlive** [Ziggeo/ReactNativeSDK#8]
Add new ZiggeoPackage() to the list returned by the getPackages() method is in MainApplication, not MainActivity.

**Comment by 3akat** [comment]
Hi @dancomanlive,
Yes, it is. Any issue with it?

**Comment by dancomanlive** [comment]
No issue but the readme needs to be updated accordingly. This is meant to help other developers that might face the same issue.

**Comment by 3akat** [comment]
@dancomanlive fixed! thank you for letting us know!
