### ISSUE TITLE
cannot build android (again)

### ISSUE THREAD

**Issue by bobananto24** [Ziggeo/ReactNativeSDK#87]
when i tried to build the react native android app I am facing this error
_Execution failed for task ':react-native-ziggeo-library:compileDebugKotlin'.
Compilation error. See log for more details_
I am facing the same error while building after updating to "react-native-ziggeo-library": "^1.6.1",(which was fixed in v1.5.4)

**Comment by 3akat** [comment]
Hi @bobananto24, looking at it

**Comment by 3akat** [comment]
In the https://github.com/Ziggeo/ReactNativeSDK/issues/76 the trouble was in `FileUtils.kt` as we can see from your log here https://github.com/Ziggeo/ReactNativeSDK/issues/76#issuecomment-922887753.  
Please share the full compilation log like you did in the last time

**Comment by bobananto24** [comment]
@3akat thanks for the instant response
this is the log you asked 
> Task :react-native-ziggeo-library:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
270 actionable tasks: 3 executed, 267 up-to-date
e: /Users/boban24/Documents/GitHub/kinky/node_modules/react-native-ziggeo-library/android/src/main/java/com/ziggeo/recorder/ZiggeoRecorderModule.kt: (364, 16): None of the following functions can be called with the arguments supplied: 
public open fun startAudioPlayer(p0: Uri): Unit defined in com.ziggeo.androidsdk.Ziggeo
public open fun startAudioPlayer(p0: String): Unit defined in com.ziggeo.androidsdk.Ziggeo

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ziggeo-library:compileDebugKotlin'.

**Comment by bobananto24** [comment]
@3akat may I know when will you publish the new update with the fix I have requested?

**Comment by 3akat** [comment]
Hey @bobananto24, will be ready during tomorrow

**Comment by 3akat** [comment]
Hi @bobananto24, please take a look at the v`1.6.2`

**Comment by bobananto24** [comment]
thanks @3akat I can build now
