### ISSUE TITLE
issues with Ziggeo.playVideo() and  Ziggeo.VideosApi.getVideoUrl()

### ISSUE THREAD

**Issue by bobananto24** [Ziggeo/ReactNativeSDK#88]
**ISSUE 1:**
Ziggeo.playVideo("VIDEO_TOKEN") gives me an error "TypeError: ZiggeoPlayer.playVideo is not a function", which is happening in "ANDROID". ( In ios simulator it's working fine)

**ISSUE 2:**
Ziggeo.VideosApi.getVideoUrl("VIDEO_TOKEN") gives me an error "TypeError: Videos.getVideoUrl is not a function", which is happening in "IOS SIMULATOR". ( In android it's working fine)

Suggest any workaround at least for any of these issues or please try to fix these as soon as you can. Thank you

**Comment by 3akat** [comment]
Hi @bobananto24, issue with the playVideo (android) fixed in `1.6.3`

**Comment by katolykdev** [comment]
Hi, @bobananto24 
Please check on current version `1.6.26`.
