### ISSUE TITLE
IOS current version not working on Apple Silicon

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#90]
Hi, I recently changed to a M1 mac and since then I can't launch the app on IOS. When I try to lunch the simulator, I have this error:
![Screen Shot 2022-01-12 at 1 31 07 PM](https://user-images.githubusercontent.com/44783494/149200749-30ccf89d-26b0-4cdb-8a41-b40736035162.png)

And when I try to launch on my device, I end up on my app loading screen but have this error and the app does not connect to my metro bundle: dyld: Library not loaded: `dyld: Library not loaded: @rpath/PINOperation.framework/PINOperation`

My project still works on my old mac. The package version that use is 1.6.4.

**Comment by katolykdev** [comment]
Hi, Sam.
Please add use_frameworks! on the Podfile.

![01](https://user-images.githubusercontent.com/64797925/149528581-d4414c5a-e836-4282-935f-fadb96deeb07.png)

**Comment by sam-houle1** [comment]
Hi @katolykdev, 
we can't use use_frameworks with flipper: https://fbflipper.com/docs/getting-started/react-native-ios/

I tried to build the library static as mentioned `[here](https://fbflipper.com/docs/getting-started/ios-native/)` but it seems to works only for old react-native version.

**Comment by Bane-D** [comment]
Hi Sam,

Can you please try to recompile your app again? My colleague had pushed the update to the current version.

Do let us know how it goes for you.

**Comment by sam-houle1** [comment]
Hi @Bane-D,
I upgraded to 1.6.5 but I still have the exact same issue.

**Comment by Bane-D** [comment]
OK. Thank you for letting us know.

Passing the info to my colleague in iOS team to look into it further.

Just to know, did you by any chance run following before compiling app:
```
cd ios
rm -rf build
xcodebuild clean
```

**Comment by sam-houle1** [comment]
I think we can close this issue, not sure what fixed it, but few weeks after I posted the error I stop getting it.
