### ISSUE TITLE
Ziggeo.playVideo(VIDEO_TOKEN) not working on ios

### ISSUE THREAD

**Issue by bobananto24** [Ziggeo/ReactNativeSDK#92]
When running Ziggeo.playVideo(VIDEO_TOKEN) in android works perfectly fine but when i try to run in ios there was no effect not even an error

**Comment by katolykdev** [comment]
Hi, @bobananto24 
You installed latest ziggeo library?
```"react-native-ziggeo-library": "1.6.6",```
I tried using this version, and it is working on my side.

If you installed latest library, could you send me package.json and Podfile?

**Comment by bobananto24** [comment]
@katolykdev I was using "react-native-ziggeo-library": "1.6.3",
Now I have updated to "react-native-ziggeo-library": "1.6.6", and after the update I couldn't build the app. 
Throwing this error:
The following build commands failed:
        CompileC /Users/boban24/Library/Developer/Xcode/DerivedData/{PROJECT_NAME}/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ZiggeoRN.build/Objects-normal/x86_64/RCTZiggeoRecorder.o /Users/boban24/Documents/GitHub/{name}/node_modules/react-native-ziggeo-library/ios/Recorder/RCTZiggeoRecorder.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'ZiggeoRN' from project 'Pods')
(1 failure)

**Comment by katolykdev** [comment]
```pod deintegrate```
```pod install```
After that, please clean the project and rebuild.

**Comment by bobananto24** [comment]
> 

still the same error
tried: 
pod deintegrate
pod install
xcodebuild clean

**Comment by bobananto24** [comment]
> `pod deintegrate` `pod install` After that, please clean the project and rebuild.

still the same error
tried:
pod deintegrate
pod install
xcodebuild clean

**Comment by katolykdev** [comment]
https://mega.nz/file/csgDyT4L#jL0sAbYDAEqEvp8ecaYTKVvsGN5Qf9pdEICvDz5YMQk
I used the package and podfile you sent.
But I can build it.
Could you retry on this project?

**Comment by bobananto24** [comment]
With "react-native-ziggeo-library": "^1.6.3", i can build the app
but when i update to "react-native-ziggeo-library": "^1.6.6", i couldn't build. 
@katolykdev

**Comment by katolykdev** [comment]
Hello, @bobananto24 
Please check on current version `1.6.26`.
