### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by yaronlevi** [Ziggeo/ReactNativeSDK#93]
Hi (-:
We are stuck on this issue for several days now and don't know what to do.
Our build (Bitrise) is failing on Ziggeo with this error:

`* What went wrong:
Could not determine the dependencies of task ':react-native-ziggeo-library:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-ziggeo-library:releaseCompileClasspath'.
   > Could not find com.github.ZiggeoJitpackService:Android-SDK:2.4.5.
     Required by:
         project :react-native-ziggeo-library`

![CleanShot 2022-03-20 at 10 19 00@2x](https://user-images.githubusercontent.com/5398977/159154087-a53d4248-7b5f-409e-8e26-338cde77a374.jpg)

We haven’t touched our codebase. Meaning the exact same commit worked well and passed the build a few days ago. It seems like there is some error when trying to fetch the library.

Any help would be much appriciated.

**Comment by yaronlevi** [comment]
Update:
We've updated Ziggeo to the latest version 1.6.7 and now we get a different error regarding the [Mediapipe](https://google.github.io/mediapipe/) lib:
![CleanShot 2022-03-22 at 16 43 42@2x](https://user-images.githubusercontent.com/5398977/159508654-53fa2d46-70f5-47dd-ab08-e9a666801fca.jpg)

**Comment by 3akat** [comment]
@yaronlevi can you please try the previous version, the issue with `2.4.5` should be fixed

**Comment by yaronlevi** [comment]
> @yaronlevi can you please try the previous version, the issue with `2.4.5` should be fixed
I don't understand. Which version of react-native-ziggeo-library should be good now? 
׳יאש

**Comment by 3akat** [comment]
@yaronlevi we're still working on `1.6.7`, so please try the version you used when opened this issue

**Comment by yaronlevi** [comment]
@3akat ok, 1.6.4 is working again. Thank you!
