### ISSUE TITLE
Android not building since 1.6.6

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#94]
Hi, I was using 1.6.4 and after upgrading the package I have an error that prevent me from building the application:

`
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.1.
     AAR metadata file: /Users/samuelhoule/.gradle/caches/transforms-3/abf7aafa4f162b379e6de3ac273aab48/transformed/work-runtime-2.7.1/META-INF/com/android/build/gradle/aar-metadata.properties.
`

I can't go back to 1.6.4, the version 1.6.4 was not working for IOS somehow.

Anyone have the same issue ?

**Comment by bobananto24** [comment]
I have the same issue now but with 1.6.4 I could build in both ios and android

**Comment by sam-houle1** [comment]
@bobananto24 did you manage to fix this issue ? I tried to force work:work-runtime:2.7.1 but it didn't work.

**Comment by 3akat** [comment]
Hi @sam-houle1!
First of all please try the latest version, currently it's `1.6.8`. If the issue still exists please tell what is the verions of `compileSdkVersion` in android part of your project.

**Comment by sam-houle1** [comment]
On 1.6.8 I was having the same error, I changed the compileSdkVersion to 31 (was 30) and it fixed my error. 

Closing this issue.
