### ISSUE TITLE
Implicit conversion of 'int' to 'NSSString *' is disallowed with ARC on ios 1.6.4

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#95]
Hi, I was using 1.6.4 for the past months and out of nowhere it stoped working. 
Here's the issue:
![Screen Shot 2022-03-23 at 12 59 35 PM](https://user-images.githubusercontent.com/44783494/159755119-41f3b85d-188c-41a5-84f9-1f2a7290aa25.png)

I can't upgrade to 1.6.6 because android is not working due to [this issue](https://github.com/Ziggeo/ReactNativeSDK/issues/94).

Can this get fix quick ? I can't do any release on my app.

**Comment by 3akat** [comment]
Hi @sam-houle1, we're working on releasing fixed version asap

**Comment by sam-houle1** [comment]
Hi @3akat do you guys have an ETA ?

**Comment by 3akat** [comment]
@sam-houle1 should be fixed in a day or two

**Comment by sam-houle1** [comment]
@3akat hi, is this issue going to be fixed this week ?

**Comment by 3akat** [comment]
hey @sam-houle1, please try with the latest version, android issues should be resolved

**Comment by sam-houle1** [comment]
Fixed, closing this issue.
