### ISSUE TITLE
Cannot build IOS with version 1.6.9

### ISSUE THREAD

**Issue by bobananto24** [Ziggeo/ReactNativeSDK#97]
The last version which I can build both android and IOS was version 1.6.4. Whenever I try to upgrade from 1.6.4 I cannot build IOS. I cannot use 1.6.4 in my project as the version has issue in IOS while playing ziggeo recorded video.

I have even tried removing Pods and cleaned the build folder. But still it didn't work.

This is the error message I got while building:
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/boban24/Library/Developer/Xcode/DerivedData/Project-ejfaqqgzgmzhatetoynnwfabliuu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ZiggeoRN.build/Objects-normal/x86_64/RCTVideos.o /Users/boban24/Documents/GitHub/reactnative/node_modules/react-native-ziggeo-library/ios/Videos/RCTVideos.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'ZiggeoRN' from project 'Pods')
(1 failure)

**Comment by katolykdev** [comment]
Hello, @bobananto24 
Please check on current version `1.6.26`.
