### ISSUE TITLE
Camera switch is not working on android

### ISSUE THREAD

**Issue by sam-houle1** [Ziggeo/ReactNativeSDK#99]
Hi,  on Android, when I try to switch camera from rear to front nothing happens. I have setCameraSwitchEnabled(true) so the button displays and I can interact with it, but the camera doesn't switch from rear to front.

**Comment by 3akat** [comment]
hey @sam-houle1, checking it

**Comment by 3akat** [comment]
@sam-houle1 can you please specify the version you use and also share some logs? Everything works fine with the latest versiob

**Comment by sam-houle1** [comment]
@3akat hi, im on 1.6.8. also I have nothing in my console. But here's how we've implemented our code :

`Ziggeo.setExtraArgsForRecorder({
            video_profile: HD_VIDEO_PROFILE,
        });
        
        Ziggeo.setAppToken(ZIGGEO_APP_TOKEN);
        Ziggeo.setCameraSwitchEnabled(true);
        Ziggeo.setCoverSelectorEnabled(true);
        Ziggeo.setCamera(Ziggeo.REAR_CAMERA);
        const token = await Ziggeo.startCameraRecorder();`

**Comment by 3akat** [comment]
@sam-houle1 thanks for the info! is that also possible to share the device and android version you're using?

**Comment by sam-houle1** [comment]
@3akat device info : Samsung A5 (SM-A530W) and the version is 9.

**Comment by sam-houle1** [comment]
@3akat one of my co-worker has a LG G8 version 11 and it's working for him

**Comment by 3akat** [comment]
@sam-houle1 please try version '1.6.11'

**Comment by sam-houle1** [comment]
@3akat thanks it's working now.
